name: Deploy to WordPress.org
'on':
  release:
    types:
      - released
jobs:
  deploy:
    name: Deploy to WP.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # - name: Install Node and npm.
      #   uses: actions/setup-node@v3
      
      # - name: Install NPM dependencies
      #   run: npm install
      # - name: Build
      #   run: |
      #     npm install
      #     npm run build:all

      - name: Install SVN ( Subversion )
        run: |
          sudo apt-get update
          sudo apt-get install subversion
      
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_USERNAME: '${{ secrets.SVN_USERNAME }}'
          SVN_PASSWORD: '${{ secrets.SVN_PASSWORD }}'
          SLUG: ultra-elementor-addons
